### PR TITLE
Update README.md (For https://github.com/yairm210/Unciv/pull/5895)

### PR DESCRIPTION
**Pull request by will-ca**
https://github.com/yairm210/Unciv/pull/5895

### CODE REVIEW

**Comment by will-ca** [comment]
summary

**Comment by will-ca** [comment]
merge translations

**Comment by will-ca** [comment]
Translations branch created

**Comment by Intralexical** [comment]
summary

**Comment by Intralexical** [comment]
merge translations

**Comment by will-ca** [comment]
I have now restored the original bots without the check for user privileges, which means that rando account should be able to trigger events now.

**Comment by Intralexical** [comment]
summary

**Comment by Intralexical** [comment]
merge translations

**Comment by will-ca** [comment]
Translations PR created

**Pull request closed without merging**
